version: '3'
services:
  chai_research:
    # platform: linux/amd64
    build:
      context: ./
      args:
        - USER_NAME=chai_research
        - USER_UID=1000
        - USER_GID=1000
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/chai_research/project/chai_research
    command: [
      "jupyter", "lab",
      "--ip", "${HOST_IP}",
      "--port", "8888",
      "--no-browser"
    ]
