version: '3'
services:
  python:
    # platform: linux/amd64
    build:
      context: chai_research/docker
      args:
        - USER_NAME=chai_research
        - USER_UID=1000
        - USER_GID=1000
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ../:/home/${USER_NAME}/project/chai_research
    command: [
      "jupyter", "lab",
      "--ip", "${HOST_IP}",
      "--port", "8888",
      "--no-browser"
    ]
